package com.example.cinema.api;

import com.example.cinema.entity.Content;
import com.example.cinema.entity.MediaAsset;
import com.example.cinema.entity.User;
import com.example.cinema.infra.s3.PresignService;
import com.example.cinema.infra.s3.S3ObjectService;
import com.example.cinema.repository.content.ContentRepository;
import com.example.cinema.repository.user.UserRepository;
import com.example.cinema.service.asset.MediaAssetService;
import com.example.cinema.service.asset.S3KeyFactory;
import com.example.cinema.service.encoding.EncodingJobService;
import com.example.cinema.type.AssetType;
import com.example.cinema.type.Visibility;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.*;
import software.amazon.awssdk.services.s3.model.HeadObjectResponse;

import java.net.URL;

@RestController
@RequiredArgsConstructor
@RequestMapping("/api/assets")
public class AssetUploadController {

    private final PresignService presignService;
    private final S3ObjectService s3ObjectService;
    private final S3KeyFactory keyFactory;

    private final UserRepository userRepository;
    private final ContentRepository contentRepository;
    private final MediaAssetService mediaAssetService;
    private final EncodingJobService encodingJobService;

    @Value("${upload.verify.video_min_bytes}")
    private long videoMinBytes;

    @Value("${upload.verify.image_min_bytes}")
    private long imageMinBytes;

    @Value("${aws.cloudfront.domain}")
    private String cfDomain;

    public record PresignReq(
            @NotNull AssetType assetType,
            @NotNull Long ownerUserId,
            Long contentId,
            @NotBlank String fileName,
            @NotBlank String contentType
    ) {
    }

    public record PresignRes(String objectKey, String uploadUrl) {
    }

    @PostMapping("/presign")
    public PresignRes presign(@RequestBody PresignReq req) {
        String key = switch (req.assetType()) {
            case POSTER_IMAGE -> {
                if (req.contentId() == null) {
                    throw new IllegalArgumentException("contentId required for POSTER_IMAGE");
                }
                yield keyFactory.posterKey(req.contentId(), req.contentType(), req.fileName());
            }
            case VIDEO_SOURCE -> {
                if (req.contentId() == null) {
                    throw new IllegalArgumentException("contentId required for VIDEO_SOURCE");
                }
                yield keyFactory.videoSourceKey(req.contentId());
            }
            case PROFILE_IMAGE -> "profiles/" + req.ownerUserId() + "/profile.jpg";
            case VIDEO_HLS_MASTER -> throw new IllegalArgumentException("VIDEO_HLS_MASTER is generated by server");
        };

        URL url = presignService.presignPut(key, req.contentType());
        return new PresignRes(key, url.toString());
    }

    public record CompleteReq(
            @NotNull AssetType assetType,
            @NotNull Long ownerUserId,
            Long contentId,
            @NotBlank String objectKey,
            @NotBlank String contentType,
            Visibility visibility
    ) {
    }

    public record CompleteRes(String status, String cdnUrl, String jobId) {
    }

    @PostMapping("/complete")
    public CompleteRes complete(@RequestBody CompleteReq req) {
        User owner = userRepository.findById(req.ownerUserId())
                .orElseThrow(() -> new IllegalArgumentException("user not found: " + req.ownerUserId()));

        Visibility visibility = (req.visibility() == null) ? Visibility.PUBLIC : req.visibility();

        if (req.assetType() == AssetType.POSTER_IMAGE) {
            if (req.contentId() == null) {
                throw new IllegalArgumentException("contentId required for POSTER_IMAGE");
            }

            HeadObjectResponse head = s3ObjectService.assertReady(
                    req.objectKey(), imageMinBytes, "image/", 3, new long[]{300, 600, 1200}
            );

            Content content = contentRepository.findById(req.contentId())
                    .orElseThrow(() -> new IllegalArgumentException("content not found: " + req.contentId()));

            MediaAsset poster = mediaAssetService.createAsset(
                    owner, AssetType.POSTER_IMAGE, req.objectKey(), req.contentType(), visibility, head
            );
            mediaAssetService.attachToContent(content, AssetType.POSTER_IMAGE, poster);

            return new CompleteRes("OK", "https://" + cfDomain + "/" + req.objectKey(), null);
        }

        if (req.assetType() == AssetType.VIDEO_SOURCE) {
            if (req.contentId() == null) {
                throw new IllegalArgumentException("contentId required for VIDEO_SOURCE");
            }

            HeadObjectResponse head = s3ObjectService.assertReady(
                    req.objectKey(), videoMinBytes, "video/", 3, new long[]{500, 1000, 2000}
            );

            Content content = contentRepository.findById(req.contentId())
                    .orElseThrow(() -> new IllegalArgumentException("content not found: " + req.contentId()));

            MediaAsset src = mediaAssetService.createAsset(
                    owner, AssetType.VIDEO_SOURCE, req.objectKey(), req.contentType(), visibility, head
            );
            mediaAssetService.attachToContent(content, AssetType.VIDEO_SOURCE, src);

            String jobId = encodingJobService.start(req.contentId());
            return new CompleteRes("PROCESSING", null, jobId);
        }

        if (req.assetType() == AssetType.PROFILE_IMAGE) {
            HeadObjectResponse head = s3ObjectService.assertReady(
                    req.objectKey(), imageMinBytes, "image/", 3, new long[]{300, 600, 1200}
            );

            mediaAssetService.createAsset(
                    owner, AssetType.PROFILE_IMAGE, req.objectKey(), req.contentType(), visibility, head
            );

            return new CompleteRes("OK", "https://" + cfDomain + "/" + req.objectKey(), null);
        }

        throw new IllegalArgumentException("Unsupported complete type: " + req.assetType());
    }

    @PostMapping("/contents/{contentId}/encoding/retry")
    public CompleteRes retry(@PathVariable long contentId) {
        String jobId = encodingJobService.start(contentId);
        return new CompleteRes("PROCESSING", null, jobId);
    }
}
